name: pricehop_main
description: "Pricehop E-commerce App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  http: ^1.2.1
  state_notifier: ^1.0.0

  # keep the others you already added:
  provider: ^6.1.5+1
  from_css_color: ^2.0.0
  intl: ^0.18.1
  json_path: ^0.4.4
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  page_transition: ^2.2.1
  flutter_spinkit: ^5.2.2
  go_router: ^13.2.5
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
